#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"?",
"C:\\HaxeToolkit\\haxe\\std/StringTools.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Date.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/EReg.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Reflect.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Std.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/StringBuf.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Sys.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Type.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/Exception.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/NativeStackTrace.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/ds/StringMap.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/sys/FileSystem.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/sys/io/File.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/sys/io/FileOutput.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/SysTools.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/ValueException.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/exceptions/NotImplementedException.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/exceptions/PosException.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/format/JsonParser.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/format/JsonPrinter.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/io/Bytes.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/io/Output.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/io/Path.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/iterators/ArrayIterator.hx",
"blue/BHaxeUtil.hx",
"blue/BLexer.hx",
"blue/BParser.hx",
"blue/Blue.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"C:\\Users\\magnu\\Desktop\\Blue\\?",
"C:\\HaxeToolkit\\haxe\\std\\StringTools.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Date.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\EReg.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Reflect.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Std.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\StringBuf.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Sys.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Type.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\Exception.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\NativeStackTrace.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\ds\\StringMap.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\sys\\FileSystem.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\sys\\io\\File.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\sys\\io\\FileOutput.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\SysTools.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\ValueException.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\exceptions\\NotImplementedException.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\exceptions\\PosException.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\format\\JsonParser.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\format\\JsonPrinter.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Bytes.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Output.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Path.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\iterators\\ArrayIterator.hx",
"C:\\Users\\magnu\\Desktop\\Blue\\blue\\BHaxeUtil.hx",
"C:\\Users\\magnu\\Desktop\\Blue\\blue\\BLexer.hx",
"C:\\Users\\magnu\\Desktop\\Blue\\blue\\BParser.hx",
"C:\\Users\\magnu\\Desktop\\Blue\\blue\\Blue.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"Date",
"EReg",
"Reflect",
"Std",
"StringBuf",
"haxe.SysTools",
"StringTools",
"Sys",
"Type",
"blue.BHaxeUtil",
"blue.BLexer",
"blue.BParser",
"blue.Blue",
"haxe.Exception",
"haxe.NativeStackTrace",
"haxe.ValueException",
"haxe.ds.StringMap",
"haxe.exceptions.PosException",
"haxe.exceptions.NotImplementedException",
"haxe.format.JsonParser",
"haxe.format.JsonPrinter",
"haxe.io.Bytes",
"haxe.io.Output",
"haxe.io.Path",
"haxe.iterators.ArrayIterator",
"sys.FileSystem",
"sys.io.File",
"sys.io.FileOutput",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(::hx::__hxcpp_all_classes, ::hx::__hxcpp_all_files_fullpath); }
